# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Kitahara Saneyuki
email: edwarddwarf1999@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
domain: kitahara-saneyuki.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://kitahara-saneyuki.github.io  # the base hostname and protocol for your site, e.g. http://example.com
markdown: kramdown

author:
  name     : "Kitahara Saneyuki"
  avatar   : "/assets/images/avatar.jpeg"
  bio      : "Building stuff one commit at a time."
  location : "Ottawa, ON, Canada"
  links:
    - label: "HomeEazy"
      icon: "fas fa-fw fa-link"
      url: "https://homeeazy.com"

footer:
  links:
    - label: "HomeEazy"
      icon: "fas fa-fw fa-link"
      url: "https://homeeazy.com"

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-mentions
  - jekyll-archives
  - jekyll-multiple-languages-plugin

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      classes: wide
      show_date: true
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      toc: true
  - scope:
      path: ""
      type: tag
    values:
      author_profile: true
  - scope:
      path: ""
      type: categories
    values:
      author_profile: true

logo: "./assets/images/avatar.jpeg"
breadcrumbs: true  # disabled by default

lunr:
  search_within_pages: true
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

paginate: 20
paginate_path: /articles/page:num/
timezone: America/New_York

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

permalink: /:categories/:title/
